name: warframetools
description: "Void Relic Counter & Manager for Warframe"
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  pocketbase: 
  riverpod: 
  flutter_riverpod: 
  go_router: 
  shared_preferences: 
  cached_network_image: 
  path_provider: 
  path: 
  json_annotation: 
  flutter_emoji: 
  url_launcher: 
  connectivity_plus: 
  sqlite3: 
  sqlite3_flutter_libs: 
  drift: 
  drift_flutter: 
  flutter_dotenv: 
  flutter_web_auth_2: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 
  build_runner: 
  json_serializable: 
  http: 
  drift_dev: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/icons/
    - .env
