name: warframetools
description: "Void Relic Counter & Manager for Warframe"
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.23.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  json_annotation: ^4.9.0
  flutter_emoji: ^2.1.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  json_serializable: ^6.9.3
  http: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/icons/
